[package]
name = "example"
version = "0.1.0"
authors = ["Bastian Gruber <gruberbastian@me.com>"]
edition = "2018"

[dependencies]
tide = { path = "../../tide" }
http = "0.1"
serde = "1.0.80"
serde_derive = "1.0.80"